name: Deploy genrefy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build e reinicia container
        run: |
          cd ~/genrefy
          git pull
          podman stop genrefy || true
          podman rm -f genrefy || true
          podman network rm genrefy_default || true
          sudo pkill -f aardvark-dns || true
          sudo rm -rf /run/user/$(id -u)/containers/networks/aardvark-dns || true
          podman-compose up -d --build
